### ISSUE TITLE
WorldComposer TODO

### ISSUE THREAD

**Issue by wiktor-obrebski** [alcarin-org/alcarin#2]
- [x] map settings
- [x] solids positions manual control
- [x] control fluid sources/sinks
- [x] simulation time step factor
- [x] simulation computational accuracy factor
- [ ] ~control external forces~
- [ ] ~try to move simulation to background thread~
- [ ] ~add webgl renderer~
- [x] play/pause button
- [ ] display fluid sources/sink on map
- [ ] change map size
- [ ] add forces by dragging?
- [x] change render size (zoom)
- [ ] fix sinks close-to-wall bug

Cleanup:
- [x] refactor statistics
- [x] restore pressure view
- [ ] fix simulations unit tests
- [x] refactor `App.ts`
- [x] think about drop React components in favor of plain functions on PixelImageData renderers (for performance and simplicity)

**Comment by wiktor-obrebski** [comment]
Web workers tests summary:
 - not supported yet without `eject` in CRA: https://github.com/facebook/create-react-app/pull/5886
 - in standard case data are shared by copy. as we need to handle thousands of particles and update them dozens times per second, the copy  mechanism starts to be significant blocker
 - there is a "Transferable" way of sharing data in newest Chrome. it allow as that second thread not only update given particles, but even prepare draw buffer to be renderer on main thread later
 - generally, it's interesting topic and I should back to it in the future. currently prefer to spend time somewhere else (and not ejecting entire app)

**Comment by wiktor-obrebski** [comment]
webgl renderer summary:
 - after some test I decided that there is too big learning cost to do it right and not enough to gain. currently rendering isn't any real problem, recalculating particles positions is bottleneck

**Comment by wiktor-obrebski** [comment]
I focusing on main project currently, abandoning this toy project.
